export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const FETCH_SUGGESTION_FRIENDS_REQUEST =
  'FETCH_SUGGESTION_FRIENDS_REQUEST';
export const FETCH_SUGGESTION_FRIENDS_SUCCESS =
  'FETCH_SUGGESTION_FRIENDS_SUCCESS';
export const FETCH_SUGGESTION_FRIENDS_FAIL = 'FETCH_SUGGESTION_FRIENDS_FAIL';

export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_RECEIVER_FRIENDS_REQUEST = 'FETCH_RECEIVER_FRIENDS_REQUEST';
export const FETCH_RECEIVER_FRIENDS_SUCCESS = 'FETCH_RECEIVER_FRIENDS_SUCCESS';
export const FETCH_RECEIVER_FRIENDS_FAIL = 'FETCH_RECEIVER_FRIENDS_FAIL';

export const FETCH_CURRENT_FRIENDS_REQUEST = 'FETCH_CURRENT_FRIENDS_REQUEST';
export const FETCH_CURRENT_FRIENDS_SUCCESS = 'FETCH_CURRENT_FRIENDS_SUCCESS';
export const FETCH_CURRENT_FRIENDS_FAIL = 'FETCH_CURRENT_FRIENDS_FAIL';

export const FETCH_SENT_FRIENDS_REQUEST = 'FETCH_SENT_FRIENDS_REQUEST';
export const FETCH_SENT_FRIENDS_SUCCESS = 'FETCH_SENT_FRIENDS_SUCCESS';
export const FETCH_SENT_FRIENDS_FAIL = 'FETCH_SENT_FRIENDS_FAIL';
